FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm ci

COPY server ./server
COPY tsconfig*.json ./

RUN npm run prisma:generate && npm run build:api

EXPOSE 3334

CMD ["node", "dist-server/index.js"]
